apiVersion: v1
kind: Service
metadata:
  name: witix-kibana-svc
  labels:
    component: kibana
spec:
  type: LoadBalancer
  selector:
    component: kibana
  ports:
  - name: http
    port: 5601
    protocol: TCP
