apiVersion: v1
kind: ReplicationController
metadata:
  name: witix-kibana
  labels:
    component: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        image: ciandtsoftware/witix-kibana:3.0.2-alpha
        imagePullPolicy: Always
        env:
          - name: ELASTICSEARCH_URL
            value: "http://elasticsearch:9200"
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP